# Site settings
title: Prueba presentacion
description: Una breve prueba para practicar Markdown

# Theme settings
theme: jekyll-theme-architect

# Markdown settings
markdown: kramdown

# Github Pages settings
github:
  repository: Adrian-glz01/Adrian-glz01.github.io
